FROM ubuntu:20.04
MAINTAINER souravshah22@gmail.com

RUN apt-get update -y
RUN apt-get install python3-pip -y 

COPY requirements.txt requirements.txt
COPY flaskapp /opt/

RUN pip3 install -r requirements.txt
WORKDIR /opt/

CMD python3 app.py
